### ISSUE TITLE
Examples does not work on Asus Zenfone AR

### ISSUE THREAD

**Issue by lvonasek** [googlesamples/tango-examples-c#110]
There's a dlopen failure: libtango_client_api.so was not found. That caused a fatal error in TangoInitHelper.loadLibrary.

Discussed here: https://github.com/lvonasek/tango/issues/9

**Comment by rayhero** [comment]
I try it but it works on Zenfone AR

**Comment by lvonasek** [comment]
ok, I am closing the issue - maybe it was connected with old core
