### ISSUE TITLE
Runtime error: could not load libraries

### ISSUE THREAD

**Issue by MallikarjunTirlapur** [googlesamples/tango-examples-c#28]
Hi,
The code hello-tango-jni successfully & installed in tango. But whe i tried to open the app, I am seeing this error across logcat.  Can you please give me the solution?

09-22 07:56:37.680: E/AndroidRuntime(32037): Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libtango_client_api.so" needed by "libtango-native-jni.so"; caused by load_library(linker.cpp:745): library "libtango_client_api.so" not found

**Comment by monsuree** [comment]
Fin
