### ISSUE TITLE
OpenGL ES 3.0

### ISSUE THREAD

**Issue by sjfricke** [googlesamples/tango-examples-c#98]
Why is the tango_gl running OpenGL ES 2.0? 

The Dev Kit runs Android 4.4 and can run OpenGL ES 3.0

There is no Tango device therefore not able to use 3.0 and 2.0 is missing a LOT of needed features

**Comment by sjfricke** [comment]
Also the work around I found for people using the Dev Kit still
http://stackoverflow.com/questions/33764617/using-opengl-es-3-1-on-google-tango

**Comment by chaosemer** [comment]
Hi!

Feel free to use your own rendering engine in its place! tango-gl is written to be easy to read, even if that would be less efficient. So we've avoided doing common optimizations like caching the GL state or using GPU-side vertex buffers where it would obscure the code.

I'm going to close this, if you have particular questions about how to support GLES 3 for Tango, please open another issue.

**Comment by sjfricke** [comment]
I also just found out there is no need for this as you can just change the manifest file from 

`<uses-feature android:glEsVersion="0x00020000" android:required="true" />`
to
`<uses-feature android:glEsVersion="0x00030000" android:required="true" />`
